services:
  # Database service for PostgreSQL
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: campusconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis service for Celery and Django Channels
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  # Web service for Django app
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/code
      - staticfiles:/app/staticfiles  # Ensure static files are properly mounted
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    # Adding an entrypoint to collectstatic automatically when the container starts
    entrypoint: ["sh", "-c", "python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 core.asgi:application"]

  # Celery service for background tasks
  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  staticfiles:  # Define a volume for static files to ensure persistence

