# Generated by Django 4.2.19 on 2025-04-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.DurationField()),
                ('directions', models.TextField(help_text='Step-by-step directions')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='navigation.location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='navigation.location')),
            ],
        ),
    ]
